services:
  app:
    image: webapi
    ports:
      - "8000:8000"
    environment:
      PG_USERNAME: pguser
      PG_PASSWORD: pguser
      PG_HOSTNAME: db
      PG_DATABASE_NAME: pgdatabase
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdatabase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: