import io
import os

from urllib import request
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

pg_username = os.environ["PG_USERNAME"]
pg_password = os.environ["PG_PASSWORD"]
pg_hostname = os.environ["PG_HOSTNAME"]
pg_database_name = os.environ["PG_DATABASE_NAME"]


def main(url):
    df = None
    with request.urlopen(url) as response, io.StringIO() as buffer:
        buffer.write(response.read().decode("utf-8"))
        buffer.seek(0)
        df = pd.read_csv(buffer, sep=",")
        df["sepal_ratio"] = df["sepal_length"] / df["sepal_width"]
        df["petal_ratio"] = df["petal_length"] / df["petal_width"]
    print(df)

    try:
        connection = psycopg2.connect(
            f"dbname='{pg_database_name}' user='{pg_username}' host='{pg_hostname}' password='{pg_password}'"
        )

    except:
        print("could not connect to the database")
        exit(1)
    with connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS iristable;")
        cursor.execute(
            "CREATE TABLE iristable (index integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, sepal_length float, sepal_width float, petal_length float, petal_width float, species varchar(40), sepal_ratio float, petal_ratio float);"
        )

    engine = create_engine(
        f"postgresql://{pg_username}:{pg_password}@{pg_hostname}/{pg_database_name}"
    )
    df.to_sql("iristable", engine, if_exists="append")


main(
    "https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"
)
